# reading
# The programm make reading from *txt file
print('Открываю файл ssh.txt: ')
text_file = open('ssh.txt', 'r')
print('Читаю некоторые символы из файла')
print(text_file.read(1))
print(text_file.read(4))
print(text_file.read(10))
print('==================================================')
print('\nЧитаю остальную часть файла')
print(text_file.read())
print('Закрываю файл')
text_file.close()
print('Файл закрыт.')
print('==================================================')
print('Открываю файл ssh, ставлю кодировку utf-8, если будут русские буквы')
text_file = open('ssh.txt', 'r', encoding='utf-8')
print('Читаю строки с 1 по 5 открыторго файла, и закрываю файл')
print(text_file.readline())
print(text_file.readline())
print(text_file.readline())
print(text_file.readline())
text_file.close()
print('+++++++++++++++++++++++++++++++++++++++++++++++++++++++')
print('Просто открываю и перечитываю весь файл.')
text_file = open('ssh.txt', 'r', encoding='utf-8')
open('ssh.txt', 'r')
whole_thing = text_file.read()
print(whole_thing)
text_file.close()
print('+++++++++++++++++++++++++++++++++++++++++++++++++++++++')
print('Открываю файл ssh.txt.')
text_file = open('ssh.txt', 'r', encoding='utf-8')
print('Вывожу весь файл в одну строку')
print('======================================')
lines = text_file.readlines()
print(lines)
print('======================================')
print('Выводим количество строк в файле')
print(len(lines))
print('======================================')
print('Печатаем строки файла')
for line in lines:
    print(line)
print('и закрываю файл...')
text_file.close()
print('======================================')
print('Перебор строк файла.')
text_file = open('ssh.txt', 'r', encoding='utf-8')
for line in text_file:
    print(line)
text_file.close()
input('\n\nНажмите Enter, чтобы выйти.')
print('*************************************')


